Lang.prototype.pack.sw = {
	"token": {
		"Wage Calculator":"Kokotozi Mshahara",
		"Living Wage":"Gharama za Maisha",
		"Are you being paid enough?":"Je, mwajiri wako anakulipa kiasi cha kutosha?",
		"How much does your employer pay you?":"Je, unalipwa kiasi gani?",
		"per day":"kwa siku",
		"per week":"kwa wiki",
		"per month":"kwa mwezi",
		"At this rate, you are being paid the equivalent of":"Kwa kiwango hiki, unalipwa sawa na",
		"Calculate expenses":"Kokotoa matumizi",
		"This covers":"Hii inatosheleza asilimia ",
		"of your household's minimal need of":"ya kiasi cha chini mnachokihitaji kama kaya, nacho ni ",
		"Show assumptions":"Onyesha dhana",
		"Assumptions":"Dhana",
		"Our calculations are based on":"Mahesabu yetu yanategemea",
		"8 assumptions":"dhana 8",
		"Household Size":"Ukubwa wa Kaya",
		"people":"watu",
		"Including yourself,":"Ni watu wangapi wanakutegemea nyumbani kwako, ukijihesabu na wewe mwenyewe?",
		"how man people in your household are you responsible for":" ",
		"of domestic workers are known to be sole income providers for their households.":"ya wafanyakazi wa ndani wanajulikana kuwa watoaji wa mapato pekee kwa kaya zao.",
		"Source:":"Chanzo:",
		"Sources:":"Vyanzo:",
		"Food Cost":"Gharama za Chakula",
		"What do you estimate are your daily":"Je, gharama ya chakula kwa kila mtu mmoja mmoja nyumbani kwako ni kiasi gani, kwa makadirio?",
		"food costs":" ",
		"per person in your household?":" ",
		"Transportation Cost":"Gharama za Usafiri",
		"How much does it cost you to":"Unatumia shilingi ngapi",
		"get to work":"kwenda kazini",
		"one way":"kwenda tu",
		"roundtrip":"kwenda na kurudi",
		"Is this cost":"Gharama hii ni",
		"or for a":"au ni",
		"Housing Cost":"Gharama za Makazi",
		"How much are you paying for":"Unalipa kodi kiasi gani, na",
		"rent and utility costs":"bili zingine",
		"(including electricity)?":"(kama umeme)?",
		"Generally speaking, higher rents are associated with better provision of sanitation services and lower crime rates.":"Kwa kawaida, kodi kubwa ya nyumba inahusishwa na upatikanaji mzuri wa huduma za afya na kiwango kidogo cha uhalifu eneo hilo.",
		"Healthcare Cost":"Gharama za Huduma ya Afya",
		"What is your monthly allowance for":"Je, unatumia kiasi gani kujilipia huduma za afya kwa mwezi",
		"healthcare":" ",
		"needs":" ",
		"Estimate a reasonable monthly health allowance (per person):":"Toa makadirio ya matumizi ya huduma ya afya kwa mwezi (kwa mtu mmoja mmoja):",
		"Education Cost":"Gharama za Elimu",
		"How much do you spend on":"Unatumia kiasi gani ",
		"sending kids to school":"kuwapeleka watoto shule",
		"Estimate the cost per school aged child:":"Toa makadirio kwa kila mtoto mwenye umri wa kwenda shule:",
		"How many school-aged children are there in the household?":"Je, kuna watoto wangapi nyumbani kwako wenye umri wa kwenda shule?",
		"Expenses include stationery, uniform, textbooks, and even transportation costs.":"Mahitaji yanajumuisha vifaa vay shule, sare, vitabu na hata gharama za usafiri.",
		"We assume two individuals in the household are in school.":"Tunadhani watu wawili katika kaya wapo shuleni.",
		"Communications Cost":"Gharama za Mawasiliano",
		"What do you estimate each member of your household spends on":"Kwa makadirio, kila mtu nyumbani kwako hutumia kiasi gani kupata huduma za",
		"communication":"mawasiliano",
		"Estimate the monthly cost per person in the household:":"Toa makadirio ya kila mmoja kwa mwezi:",
		"Communications are necessary for staying in touch with families, friends, accessing news, and for emergencies.":"Njia za mawasiliano ni za muhimu ilu kuwasiliana na ndugu, marafiki, kupata habari na kutoa au kupokea taarifa wakati unapohitaji huduma za haraka.",
		"How much would you estimate are other miscellaneous costs incurred by you and your household?":"Je, unakadiria ni kiasi gani kila mtu kwenye kaya ya mfanyakazi wako wa ndani anatumia kwa ajili ya burudani?",
		"entertainment & recreation":"burudani",
		"Estimate a monthly recreation cost per person in the household:":"Tathmini gharama za burudani za kila mwezi kwa kila mtu ndani ya kaya:",
		"It is always good to take time out from work and managing a household. Everyone needs a break!":"Daima, ni vizuri kuutumumia muda nje ya kazi na kusimamia kaya. Kila mtu anahitaji mapumziko!",
		"Other Costs":"Gharama Nyingine",
		"How much would you estimate are":"Unadhani wewe na wa nyumbani kwako mnapata kiasi gani kwa ajili ya ",
		"other miscellaneous costs":"mahitaji mengine",
		"incurred by your domestic worker's household?":"ambayo si ya kupanga?",
		"These include clothing, household items, personal care, and emergency expenses. Estimate other costs incurred per person in the household.":"Hizi ni pamoja na nguo, vitu vya kaya, huduma binafsi, na gharama za dharura. Tathmini gharama nyingine zinazohusika na kila mtu katika kaya.",
		"This should including for emergencies and procurement of durable goods, transportation of goods (gas cylinders, groceries, etc), implicit and explicit costs of running a household.":"Hii inapaswa kuhusisha kwa dharura na ununuzi wa bidhaa za kudumu, usafirishaji wa bidhaa (gesi, magurudumu, nk), gharama za wazi na zisizo wazi za kuendesha kaya.",
		"Using your input, we've calculated the minimum amount you should pay your domestic worker.":"Kutumia taarifa zako, tumekokotoa kiwango cha chini unachopaswa kumlipa mfanyakazi wako wa nyumbani.",
		"Click here to see the results":"Bonyeza hapa kuona matokeo",
		"Brought to you by":"Imeletwa kwako na",
		"Fork this on GitHub":"Iume hii kwenye GitHub",
		"1 day per week":"siku 1 kwa wiki",
		"2 days per week":"Siku 2 kwa wiki",
		"3 days per week":"Siku 3 kwa wiki",
		"4 days per week":"Siku 4 kwa wiki",
		"5 days per week":"Siku 5 kwa wiki",
		"6 days per week":"Siku 6 kwa wiki",
		"7 days per week":"Siku 7 kwa wiki",
	},
	"regex": [
	]
};