Lang.prototype.pack.sw = {
	"token": {
		"Wage Calculator":"Kokotozi Mshahara",
		"Living Wage":"Gharama za Maisha",
		"Are you paying your domestic worker enough?":"Je, mfanyakazi wako wa nyumbani unamlipa kiasi cha kutosha?",
		"How much do you pay your household worker?":"Unamlipa kiasi gani mfanyakazi wako wa nyumbani?",
		"per day":"kwa siku",
		"per week":"kwa wiki",
		"per month":"kwa mwezi",
		"At this rate, you are paying the equivalent of":"Kwa kiwango hiki, unalipa sawa na",
		"Calculate expenses":"Kokotoa matumizi",
		"This covers":"Hii inajumuisha",
		"of the household's minimal need of":"ya mahitaji ya chini ya kaya ya",
		"Show assumptions":"Onyesha dhana",
		"Assumptions":"Dhana",
		"Our calculations are based on":"Mahesabu yetu yanategemea",
		"8 assumptions":"dhana 8",
		"Household Size":"Ukubwa wa Kaya",
		"people":"watu",
		"Including your domestic worker":"Kujumuisha mfanyakazi wako wa ndani",
		"how large is their household":" ukubwa wa kaya zao ni upi",
		"of domestic workers are known to be sole income providers for their households.":"ya wafanyakazi wa ndani wanajulikana kuwa watoaji wa mapato pekee kwa kaya zao.",
		"Source:":"Chanzo:",
		"Sources:":"Vyanzo:",
		"Food Cost":"Gharama za Chakula",
		"What do you estimate are the daily":"Je! Unakadiria ni gharama zipi za kila siku za",
		"food costs":"chakula",
		"per person in your domestic worker's household?":"kwa kila mtu kwenye kaya ya mfanyakazi wako wa ndani?",
		"Transportation Cost":"Gharama za Usafiri",
		"How much does it cost your domestic worker to":"Inagharimu kiasi gani kwa mfanyakazi wako wa nyumbani",
		"get to work":"kufika kazini",
		"one way":"kwenda tu",
		"roundtrip":"kwenda na kurudi",
		"Is this cost":"Gharam hii ni",
		"or for a":"au ni",
		"Housing Cost":"Gharama za Makazi",
		"How much do you estimate are your domestic worker's":"Unakadiria kuwa wafanyakazi wako wa nyumbani wanatumia kiasi gani kwa",
		"rent and utility costs":"kulipa kodi na kulipa bili mbalimbali",
		"(including electricity)?":"(ukijumuisha na umeme)?",
		"Generally speaking, higher rents are associated with better provision of sanitation services and lower crime rates.":"Kwa kawaida, kodi kubwa ya nyumba inahusishwa na upatikanaji mzuri wa huduma za afya na kiwango kidogo cha uhalifu.",
		"Healthcare Cost":"Gharama za Huduma ya Afya",
		"What is a reasonable monthly allowance for":"Ni malipo yapi mazuri ya kila mwezi kwa ajili ya mahitaji ya",
		"healthcare":"huduma za afya",
		"needs":" ",
		"Estimate a reasonable monthly health allowance (per person):":"Kadiria malipo mazuri ya afya kwa mwezi (kwa mtu):",
		"Education Cost":"Gharama za Elimu",
		"What much do you estimate your domestic worker spends on":"Je! Unakadiria ni kiasi gani mfanyakazi wako wa ndani hutumia",
		"sending kids to school":"kuwapeleka watoto shuleni",
		"Estimate the cost per school aged child:":"Kadiria gharama ya kila mtoto aliyefikia umri wa shule:",
		"How many school-aged children are there in the household?":"Je, ni watoto wangapi waliofikia umri wa shule waliopo kwenye kaya?",
		"Expenses include stationery, uniform, textbooks, and even transportation costs.":"Gharama zinajumuisha vifaa vya maandishi, sare, vitabu na hata gharama za usafiri.",
		"We assume two individuals in the household are in school.":"Tunadhani watu wawili katika kaya wapo shuleni.",
		"Communications Cost":"Gharama za Mawasiliano",
		"What do you estimate each member of your domestic worker's household spends on":"Je, unakadiria ni kiasi gani kila mtu kwenye kaya ya mfanyakazi wako wa ndani anatumia kwa ajili ya",
		"communication":"mawasiliano",
		"Estimate the monthly cost per person in the household:":"Tathmini gharama za kila mwezi kwa kila mtu ndani ya kaya:",
		"Communications are necessary for staying in touch with families, friends, accessing news, and for emergencies.":"Mawasiliano ni muhimu kwa kuwasiliana na kuwa karibu na familia, marafiki, kupata habari, na dharura.",
		"Recreation Cost":"Gharama za Burudani",
		"How much do you estimate each household members spends on":"Je, unakadiria ni kiasi gani kila mtu kwenye kaya ya mfanyakazi wako wa ndani anatumia kwa ajili ya",
		"entertainment & recreation":"burudani",
		"Estimate a monthly recreation cost per person in the household:":"Tathmini gharama za burudani za kila mwezi kwa kila mtu ndani ya kaya:",
		"It is always good to take time out from work and managing a household. Everyone needs a break!":"Daima, ni vizuri kuutumumia muda nje ya kazi na kusimamia kaya. Kila mtu anahitaji mapumziko!",
		"Other Costs":"Gharama Nyingine",
		"How much would you estimate are":"Je, unakadiria ni",
		"other miscellaneous costs":"gharama zipi zingine za aina tofauti",
		"incurred by your domestic worker's household?":"zilizopo kwenye kaya ya mfanyakazi wako wa nyumbani?",
		"These include clothing, household items, personal care, and emergency expenses. Estimate other costs incurred per person in the household.":"Hizi ni pamoja na nguo, vitu vya kaya, huduma binafsi, na gharama za dharura. Tathmini gharama nyingine zinazohusika na kila mtu katika kaya.",
		"This should including for emergencies and procurement of durable goods, transportation of goods (gas cylinders, groceries, etc), implicit and explicit costs of running a household.":"Hii inapaswa kuhusisha kwa dharura na ununuzi wa bidhaa za kudumu, usafirishaji wa bidhaa (gesi, magurudumu, nk), gharama za wazi na zisizo wazi za kuendesha kaya.",
		"Using your input, we've calculated the minimum amount you should pay your domestic worker.":"Kutumia taarifa zako, tumekokotoa kiwango cha chini unachopaswa kumlipa mfanyakazi wako wa nyumbani.",
		"Click here to see the results":"Bonyeza hapa kuona matokeo",
		"Brought to you by":"Imeletwa kwako na",
		"Fork this on GitHub":"Iume hii kwenye GitHub",
		"1 day per week":"siku 1 kwa wiki",
		"2 days per week":"Siku 2 kwa wiki",
		"3 days per week":"Siku 3 kwa wiki",
		"4 days per week":"Siku 4 kwa wiki",
		"5 days per week":"Siku 5 kwa wiki",
		"6 days per week":"Siku 6 kwa wiki",
		"7 days per week":"Siku 7 kwa wiki",
	},
	"regex": [
	]
};